version: '2.4'
services:

  keras-py27-jupyter-eunsoo:
    image: encoredtechr/deepo:keras-py27-jupyter-cudnn7.0
    depends_on:
      - cuda-9-0_cudnn-7-0-${CONTAINER_PREFIX}
    ports:
      - 10000:8888
    environment:
      - HOME=${HOME}
      - JUPYTER_PASSWD=${JUPYTER_PASSWD}
    volumes:
      - ${HOME}:${HOME}
      - ./jupyter-config:${HOME}/.jupyter
    runtime: nvidia
    command: jupyter notebook

  cuda-9-0_cudnn-7-0-eunsoo:
    image: encoredtechr/cuda:9.0-cudnn7.0
